### PR TITLE
fix: Add SourceGenTask to fix local build

### PR DESCRIPTION
**Pull request by Guidemarcus**
GitHub Issue: Fix local build by adding SourceGenTask

## Proposed Changes
Bug fix

## What is the current behavior?
Uno projects fail at build

## What is the new behavior?
Uno projects build

## Checklist

Please check if your PR fulfills the following requirements:

- [ ] Documentation has been added/updated
- [ ] Automated Unit / Integration tests for the changes have been added/updated
- [x] Contains **NO** breaking changes
- [ ] Updated the Changelog
- [ ] Associated with an issue

## Other information
package version is 3.2.0

### CODE REVIEW

**Review by carlh98 — APPROVED** [review]

**Comment by MatFillion** [comment]
Instead of adding Uno.SourceGenerationTask, can we update to Uno 3.11 and see if it works?

**Review by carlh98 — APPROVED** [review]

**Comment by vincentcastagna** [comment]
Its bascially a bump of Uno.UI and not adding source generation task here, right ?

**Comment by carlh98** [comment]
@vincentcastagna we should update Uno.UI to an higher version and bump also source generation task

**Comment by jeanplevesque** [comment]
Is this still relevant?
The current version is now 4.0.7

**Comment by carlh98** [comment]
Closing this PR since it's not relevant anymore

**Pull request closed without merging**
